name: Bug Report
description: Report an issue caused by NootRX
labels: ["Bug"]
projects: ["ChefKissInc/7"]
assignees:
  - VisualEhrmanntraut
body:
  - type: markdown
    attributes:
      value: |
        This form isn't for you to ask for help with your configuration; it's to report behaviour that NootRX should not be exhibiting under normal conditions!
  - type: dropdown
    id: macos_version
    attributes:
      label: macOS Version
      description: On which macOS version is the bug occurring, if not all of them? Versions that do not appear in the dropdown are not supported.
      options:
        - Big Sur (Only Navi 21)
        - Monterey
        - Ventura
        - Sonoma
        - Sequoia
    validations:
      required: false
  - type: input
    id: cpu
    attributes:
      label: What is your CPU's model?
      placeholder: ex. AMD Ryzen 5 5600X
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: What is your GPU's model?
      description: Only Navi 21-23 are supported.
      placeholder: ex. AMD Radeon RX 6600 XT
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Please describe the behaviour in detail.
      placeholder: I clicked on X, then Y and Z happened.
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: What should've happened instead?
      placeholder: X should be doing Y.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: If applicable, attach the .gpuRestart, .panic, etc file related to this issue.
      description: |
        You can find those in `/Library/Logs/DiagnosticReports`.
        If attaching a panic, make sure it was created while you have `keepsyms=1` in your boot args (else the file is useless).
